on: [push]

jobs:
  safety:
    runs-on: ubuntu-latest
    name: "safety"
    steps:
      - uses: davidslusser/actions_python_safety@v1.0.2
        with:
          options: "-i 65213"
          pip_install_command: "pip install -e .[dev]"
          python_version: "3.11"
